-- 分镜首帧 Tapflow v1：一对多要素图直接作为下一节点参考，不创建“汇聚”业务节点。
-- collect 是边/调度语义：loop 所有 iteration 完成后，gen 才启动并递归读取各子流产物。
UPDATE workflows
SET name='分镜关键帧（动态要素）',
    description='分析关联要素 → 按要素动态展开设定图 → 所有图片与额外参考直接汇入关键帧生成。',
    input_schema='{"project_id":{"type":"int","required":true},"shot_id":{"type":"int","required":true}}'::jsonb,
    output_schema='{"keyframe_url":{"type":"string"},"reference_images":{"type":"array"}}'::jsonb,
    graph=$g${
      "nodes":[
        {"id":"start","type":"start","position":{"x":40,"y":240},
         "config":{"ui":{"tap":"start","title":"开始"}}},
        {"id":"analyze","type":"action","position":{"x":380,"y":200},
         "config":{"name":"shot.ensure_elements",
                   "args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"text","title":"分析分镜关联要素","show":"summary","w":420,"h":300}}},
        {"id":"elements","type":"action","position":{"x":720,"y":520},
         "config":{"name":"shot.elements",
                   "args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"hide":true}}},
        {"id":"script","type":"action","position":{"x":700,"y":520},
         "config":{"name":"shot.keyframe.script",
                   "args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"text","title":"分镜脚本","show":"text","w":390,"h":300}}},
        {"id":"keyframe_prompt","type":"action","position":{"x":1160,"y":500},
         "config":{"name":"shot.keyframe.prompt_text",
                   "args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}",
                           "script":"{{script.text}}"},
                   "ui":{"tap":"text","title":"关键帧定格画面提示词","show":"text","w":420,"h":320}}},
        {"id":"each_element","type":"loop","position":{"x":900,"y":150},
         "config":{"source":"{{elements.items}}","body":["ensure_sheet"],"concurrency":4,
                   "failure_policy":"required_blocks",
                   "ui":{"tap":"loop","title":"要素图片生成","w":420,"h":180}}},
        {"id":"ensure_sheet","type":"subflow","position":{"x":940,"y":520},
         "config":{"slug":"element-sheet","version":1,
                   "inputs":{"project_id":"{{input.project_id}}",
                             "element_id":"{{__item__.id}}",
                             "variant_id":"{{__item__.variant_id}}"}}},
        {"id":"extra_refs","type":"action","position":{"x":900,"y":420},
         "config":{"name":"shot.keyframe.extra_references",
                   "args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"upload","title":"额外参考资产","show":"refs","w":360,"h":220}}},
        {"id":"gen","type":"gen","position":{"x":1450,"y":210},
         "config":{"modality":"image","node_id":"{{input.shot_id}}",
                   "assemble":{"name":"shot.keyframe.layers",
                     "args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}",
                             "prompt_text":"{{keyframe_prompt.text}}"}},
                   "step":"gen_keyframe","payload":{"use_storyboard":true},
                   "max_refs":10,"require_upstream_success":true,
                   "skip_if":{"sql":"SELECT meta->>'keyframe_url' FROM content_nodes WHERE id=$1",
                              "args":["{{input.shot_id}}"],"reason":"该分镜已有首帧，跳过"},
                   "ui":{"tap":"gen","title":"分镜关键帧生成","w":460,"h":273,"model":"系统出图模型"}}},
        {"id":"end","type":"end","position":{"x":1980,"y":230},
         "config":{"outputs":{"keyframe_url":"{{gen.url}}","reference_images":"{{gen.reference_images}}"},
                   "ui":{"tap":"next","title":"next · 回写分镜首帧",
                         "next":{"writes":["content_nodes.meta.keyframe_url"],"attach":true,"notify":["任务中心"]}}}}
      ],
      "edges":[
        {"from":"start","to":"analyze"},
        {"from":"analyze","to":"elements"},
        {"from":"analyze","to":"extra_refs"},
        {"from":"analyze","to":"script"},
        {"from":"script","to":"keyframe_prompt"},
        {"from":"elements","to":"each_element","mapping":"each"},
        {"from":"each_element","to":"gen","mapping":"collect"},
        {"from":"extra_refs","to":"gen","mapping":"collect"},
        {"from":"keyframe_prompt","to":"gen"},
        {"from":"gen","to":"end"}
      ]
    }$g$::jsonb,
    updated_at=now()
WHERE slug='shot-keyframe-canvas' AND version=1;
