-- 由 gen_keyframe 真实执行链反向审计得到的 Tapflow；不增加汇聚节点。
-- 文本主链：事实/连续性 → 分镜脚本 → 技能+知识装配 → 首帧质检 → 图片。
-- 图片旁路：分析要素 → 1:N 设定图，以及额外参考，直接作为 gen 的参考输入。
UPDATE workflows
SET description='真实生产依赖投影：连续性、要素与站位、分镜脚本、装配技能、知识召回、提示词质检、1:N 要素图和额外参考共同驱动一次关键帧生成。',
    graph=$g${
      "nodes":[
        {"id":"start","type":"start","position":{"x":20,"y":300},"config":{"ui":{"tap":"start","title":"开始"}}},
        {"id":"facts","type":"action","position":{"x":260,"y":260},
         "config":{"name":"shot.keyframe.context","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"text","title":"读取镜头事实","show":"summary","w":380,"h":280}}},
        {"id":"continuity","type":"action","position":{"x":700,"y":60},
         "config":{"name":"shot.assert_continuity","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"qc","title":"连续性硬门","w":300,"h":150}}},
        {"id":"analyze","type":"action","position":{"x":1060,"y":40},
         "config":{"name":"shot.ensure_elements","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"text","title":"分析分镜关联要素","show":"summary","w":390,"h":270}}},
        {"id":"blocking","type":"action","position":{"x":1480,"y":20},
         "config":{"name":"shot.ensure_blocking","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"link","title":"场景空间与站位","w":320,"h":150}}},
        {"id":"elements","type":"action","position":{"x":1420,"y":250},
         "config":{"name":"shot.elements","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},"ui":{"hide":true}}},
        {"id":"each_element","type":"loop","position":{"x":1840,"y":100},
         "config":{"source":"{{elements.items}}","body":["ensure_sheet"],"concurrency":4,"failure_policy":"required_blocks",
                   "ui":{"tap":"loop","title":"要素图片生成","w":420,"h":180}}},
        {"id":"ensure_sheet","type":"subflow","position":{"x":1840,"y":310},
         "config":{"slug":"element-sheet","version":1,"inputs":{"project_id":"{{input.project_id}}","element_id":"{{__item__.id}}","variant_id":"{{__item__.variant_id}}"}}},
        {"id":"extra_refs","type":"action","position":{"x":1840,"y":360},
         "config":{"name":"shot.keyframe.extra_references","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"upload","title":"额外参考资产","show":"refs","w":340,"h":210}}},
        {"id":"script","type":"action","position":{"x":700,"y":380},
         "config":{"name":"shot.keyframe.script","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"text","title":"分镜脚本","show":"text","w":400,"h":300}}},
        {"id":"skills","type":"action","position":{"x":700,"y":740},
         "config":{"name":"shot.keyframe.skill_manifest","args":{"project_id":"{{input.project_id}}"},
                   "ui":{"tap":"link","title":"生成技能","show":"text","w":320,"h":160}}},
        {"id":"knowledge","type":"action","position":{"x":1060,"y":700},
         "config":{"name":"shot.keyframe.knowledge","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"link","title":"出图知识召回","show":"text","w":380,"h":210}}},
        {"id":"prompt","type":"llm","position":{"x":1480,"y":500},
         "config":{"charter":"提示词生成约束：你是分镜关键帧提示词设计师。必须先使用绑定的《分镜提示词装配》技能，并结合绑定知识库与上游引用，输出一段可直接交给图片模型的中文关键帧提示词。只允许使用镜头事实与分镜脚本，不得补写剧情。必须明确唯一静态定格瞬间、主体动作、景别与焦段、角色身份和服装、场景空间与站位、时间天气光源色调；引用到的角色/场景/道具必须与上游要素一致。远景不得写面部细节，近景不得遗漏身份特征。末尾给出画风、质量以及禁止文字字幕水印约束。只输出最终提示词正文，不要标题、分析或解释。",
                   "task":"请综合全部上游引用，按提示词生成约束写出本镜唯一关键帧定格画面提示词。",
                   "skills":["legacy-skill-98"],"folder_ids":[1,5],
                   "tools":["project.info","chapter.info","shot.info"],
                   "write":{"name":"shot.set_image_prompt","args":{"shot_id":"{{input.shot_id}}","text":"{{prompt.text}}"}},
                   "ui":{"tap":"text","title":"关键帧定格画面提示词","show":"text","w":430,"h":330}}},
        {"id":"prompt_qc","type":"action","position":{"x":1960,"y":620},
         "config":{"name":"shot.review_image_prompt","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"qc","title":"首帧提示词质检","show":"text","w":340,"h":180}}},
        {"id":"prepare","type":"action","position":{"x":2340,"y":600},
         "config":{"name":"shot.prepare_keyframe","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}"},
                   "ui":{"tap":"link","title":"画幅与参考筛选","w":320,"h":150}}},
        {"id":"gen","type":"gen","position":{"x":2380,"y":180},
         "config":{"modality":"image","node_id":"{{input.shot_id}}",
                   "assemble":{"name":"shot.keyframe.layers","args":{"project_id":"{{input.project_id}}","shot_id":"{{input.shot_id}}","prompt_text":"{{prompt_qc.text}}"}},
                   "step":"gen_keyframe","payload":{"use_storyboard":true},"max_refs":10,"require_upstream_success":true,
                   "skip_if":{"sql":"SELECT meta->>'keyframe_url' FROM content_nodes WHERE id=$1","args":["{{input.shot_id}}"],"reason":"该分镜已有首帧，跳过"},
                   "ui":{"tap":"gen","title":"分镜关键帧生成","w":460,"h":273,"model":"当前激活图片模型"}}},
        {"id":"end","type":"end","position":{"x":2920,"y":210},
         "config":{"outputs":{"keyframe_url":"{{gen.url}}","reference_images":"{{gen.reference_images}}"},
                   "ui":{"tap":"next","title":"next · 保存并提供给视频","next":{"writes":["content_attachments","content_nodes.meta.keyframe_url"],"attach":true,"notify":["任务中心"]}}}}
      ],
      "edges":[
        {"from":"start","to":"facts"},{"from":"facts","to":"continuity"},{"from":"continuity","to":"analyze"},
        {"from":"analyze","to":"blocking"},{"from":"analyze","to":"elements"},{"from":"analyze","to":"extra_refs"},
        {"from":"elements","to":"each_element","mapping":"each"},
        {"from":"facts","to":"script"},{"from":"facts","to":"skills"},{"from":"skills","to":"knowledge"},
        {"from":"facts","to":"prompt"},{"from":"script","to":"prompt"},{"from":"knowledge","to":"prompt"},{"from":"blocking","to":"prompt"},
        {"from":"prompt","to":"prompt_qc"},{"from":"prompt_qc","to":"prepare"},
        {"from":"each_element","to":"gen","mapping":"collect"},{"from":"extra_refs","to":"gen","mapping":"collect"},
        {"from":"prompt_qc","to":"gen"},{"from":"prepare","to":"gen"},{"from":"gen","to":"end"}
      ]
    }$g$::jsonb,
    updated_at=now()
WHERE slug='shot-keyframe-canvas' AND version=1;
